### ISSUE TITLE
not working with default  slot  and  keepalive

### ISSUE THREAD

**Issue by eioos** [SasanFarrokh/vue-slot-loader#1]
fbindSlot.js

//to work with default  slot 
 if (typeof name == "undefined") {
        name = "default"
 }

//to work with keepalive
change life cycle created  to activated

**Comment by eioos** [comment]
//to work with mutil slots
//change  
options._slots = {
        [name]: render
}
//to
options._slots = options._slots || {}
options._slots[query.name] = render

**Comment by SasanFarrokh** [comment]
Thanks a lot, fixed on v0.0.3.
